package database

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
)

type LitestreamReplicaConfig struct {
	URLPrefix       string
	Endpoint        string
	Region          string
	AccessKeyID     string
	SecretAccessKey string
	ForcePathStyle  bool
}

type LitestreamSupervisor struct {
	enabled        bool
	bin            string
	configPath     string
	generated      bool
	replica        LitestreamReplicaConfig
	databases      map[string]struct{}
	mu             sync.Mutex
	started        bool
	startRequested bool
	ctx            context.Context
	cmd            *exec.Cmd
}

func NewLitestreamSupervisor(enabled bool, bin, configPath string) *LitestreamSupervisor {
	if strings.TrimSpace(bin) == "" {
		bin = "litestream"
	}
	return &LitestreamSupervisor{enabled: enabled, bin: bin, configPath: strings.TrimSpace(configPath), databases: make(map[string]struct{})}
}

func (s *LitestreamSupervisor) Enabled() bool {
	return s != nil && s.enabled
}

func (s *LitestreamSupervisor) Start(ctx context.Context) error {
	if !s.Enabled() {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.startRequested = true
	s.ctx = ctx
	if s.generated && len(s.databases) == 0 {
		return s.writeGeneratedConfigLocked()
	}
	return s.startLocked(ctx)
}

func (s *LitestreamSupervisor) UseGeneratedConfig(configPath string, replica LitestreamReplicaConfig) error {
	if !s.Enabled() {
		return nil
	}
	replica.URLPrefix = strings.TrimRight(strings.TrimSpace(replica.URLPrefix), "/")
	if replica.URLPrefix == "" {
		return errors.New("Litestream replica URL prefix is required when generated config is used")
	}
	if strings.TrimSpace(replica.Region) == "" {
		replica.Region = "us-east-1"
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.generated = true
	s.configPath = strings.TrimSpace(configPath)
	s.replica = replica
	return s.writeGeneratedConfigLocked()
}

func (s *LitestreamSupervisor) EnsureDatabase(dbPath string) error {
	return s.ensureDatabase(dbPath, true)
}

func (s *LitestreamSupervisor) ConfigureDatabase(dbPath string) error {
	return s.ensureDatabase(dbPath, false)
}

func (s *LitestreamSupervisor) ensureDatabase(dbPath string, start bool) error {
	if !s.Enabled() || !s.generated {
		return nil
	}
	dbPath = strings.TrimSpace(dbPath)
	if dbPath == "" {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.databases[dbPath]; ok {
		if start && s.startRequested && !s.started {
			return s.startLocked(s.ctx)
		}
		return nil
	}
	s.databases[dbPath] = struct{}{}
	if err := s.writeGeneratedConfigLocked(); err != nil {
		return err
	}
	if start && s.started {
		s.stopLocked()
	}
	if start && s.startRequested {
		return s.startLocked(s.ctx)
	}
	return nil
}

func (s *LitestreamSupervisor) startLocked(ctx context.Context) error {
	if s.started {
		return nil
	}
	if ctx == nil {
		ctx = context.Background()
	}
	args := []string{"replicate"}
	if s.configPath != "" {
		args = append(args, "-config", s.configPath)
	}
	cmd := exec.CommandContext(ctx, s.bin, args...)
	if err := cmd.Start(); err != nil {
		return err
	}
	s.started = true
	s.cmd = cmd
	go func() {
		err := cmd.Wait()
		s.mu.Lock()
		if s.cmd == cmd {
			s.started = false
			s.cmd = nil
		}
		s.mu.Unlock()
		if err != nil && !errors.Is(ctx.Err(), context.Canceled) {
			log.Printf("litestream exited: %v", err)
		}
	}()
	return nil
}

func (s *LitestreamSupervisor) Restore(dbPath string) error {
	if !s.Enabled() {
		return nil
	}
	if err := s.ConfigureDatabase(dbPath); err != nil {
		return err
	}
	args := []string{"restore", "-if-db-not-exists", "-if-replica-exists"}
	if s.configPath != "" {
		args = append(args, "-config", s.configPath)
	}
	args = append(args, dbPath)
	output, err := exec.Command(s.bin, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("litestream restore: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (s *LitestreamSupervisor) stopLocked() {
	if s.cmd == nil || s.cmd.Process == nil {
		s.started = false
		s.cmd = nil
		return
	}
	if err := s.cmd.Process.Kill(); err != nil {
		log.Printf("stop litestream: %v", err)
	}
	s.started = false
	s.cmd = nil
}

func (s *LitestreamSupervisor) writeGeneratedConfigLocked() error {
	if !s.generated {
		return nil
	}
	if s.configPath == "" {
		return errors.New("generated Litestream config path is required")
	}
	if err := os.MkdirAll(filepath.Dir(s.configPath), 0o700); err != nil {
		return err
	}
	paths := make([]string, 0, len(s.databases))
	for path := range s.databases {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var out strings.Builder
	out.WriteString("# Generated by nanoflared. Do not edit by hand.\n")
	if len(paths) == 0 {
		out.WriteString("dbs: []\n")
		return os.WriteFile(s.configPath, []byte(out.String()), 0o600)
	}
	out.WriteString("dbs:\n")
	for _, path := range paths {
		out.WriteString("  - path: ")
		out.WriteString(strconv.Quote(path))
		out.WriteString("\n")
		out.WriteString("    replica:\n")
		out.WriteString("      url: ")
		out.WriteString(strconv.Quote(s.replica.URLPrefix + "/" + filepath.Base(path)))
		out.WriteString("\n")
		if s.replica.Endpoint != "" {
			out.WriteString("      endpoint: ")
			out.WriteString(strconv.Quote(s.replica.Endpoint))
			out.WriteString("\n")
		}
		if s.replica.Region != "" {
			out.WriteString("      region: ")
			out.WriteString(strconv.Quote(s.replica.Region))
			out.WriteString("\n")
		}
		if s.replica.AccessKeyID != "" {
			out.WriteString("      access-key-id: ")
			out.WriteString(strconv.Quote(s.replica.AccessKeyID))
			out.WriteString("\n")
		}
		if s.replica.SecretAccessKey != "" {
			out.WriteString("      secret-access-key: ")
			out.WriteString(strconv.Quote(s.replica.SecretAccessKey))
			out.WriteString("\n")
		}
		if s.replica.ForcePathStyle {
			out.WriteString("      force-path-style: true\n")
		}
	}
	return os.WriteFile(s.configPath, []byte(out.String()), 0o600)
}
