/* eslint-disable */
// Generated by Nanoflare by running `nanoflare types`. DO NOT EDIT.

interface NanoflareObjectHTTPMetadata {
  contentType?: string;
}

interface NanoflareScheduledController {
  scheduledTime: number;
  cron: string;
  noRetry(): void;
}

interface NanoflareExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface NanoflareWorkerHandler<Env = unknown> {
  fetch?: (
    request: Request,
    env: Env,
    ctx: NanoflareExecutionContext,
  ) => Response | Promise<Response>;
  scheduled?: (
    controller: NanoflareScheduledController,
    env: Env,
    ctx: NanoflareExecutionContext,
  ) => void | Promise<void>;
}

interface NanoflareObjectStorageObject {
  key: string;
  size: number;
  etag: string;
  httpEtag: string;
  uploaded: Date;
  httpMetadata: NanoflareObjectHTTPMetadata;
}

interface NanoflareObjectStorageObjectBody extends NanoflareObjectStorageObject {
  body: ReadableStream | null;
  readonly bodyUsed: boolean;
  arrayBuffer(): Promise<ArrayBuffer>;
  text(): Promise<string>;
  json<T = unknown>(): Promise<T>;
  blob(): Promise<Blob>;
}

interface NanoflareObjectStoragePutOptions {
  httpMetadata?: NanoflareObjectHTTPMetadata;
}

type NanoflareObjectStoragePutValue =
  | string
  | ArrayBuffer
  | ArrayBufferView
  | Blob
  | ReadableStream
  | Request
  | Response;

interface NanoflareObjectStorageBucket {
  put(
    key: string,
    value: NanoflareObjectStoragePutValue,
    options?: NanoflareObjectStoragePutOptions,
  ): Promise<NanoflareObjectStorageObject>;
  get(key: string): Promise<NanoflareObjectStorageObjectBody | null>;
  head(key: string): Promise<NanoflareObjectStorageObject | null>;
  delete(key: string): Promise<void>;
}

interface NanoflareKVNamespace {
  get(key: string): Promise<string | null>;
  get<T = unknown>(key: string, type: "json"): Promise<T | null>;
  get(key: string, type: "arrayBuffer"): Promise<ArrayBuffer | null>;
  get(key: string, type: "stream"): Promise<ReadableStream | null>;
  put(key: string, value: string | ArrayBuffer | ArrayBufferView | ReadableStream): Promise<void>;
  delete(key: string): Promise<void>;
}

type NanoflareD1BindValue = string | number | boolean | null | ArrayBuffer | ArrayBufferView;

interface NanoflareD1Meta {
  served_by: string;
  served_by_primary: boolean;
  duration: number;
  changes: number;
  last_row_id: number;
  changed_db: boolean;
  size_after: number;
  rows_read: number;
  rows_written: number;
}

interface NanoflareD1Result<T = Record<string, unknown>> {
  success: boolean;
  meta: NanoflareD1Meta;
  results: T[];
}

interface NanoflareD1ExecResult {
  count: number;
  duration: number;
}

interface NanoflareD1PreparedStatement {
  bind(...values: NanoflareD1BindValue[]): NanoflareD1PreparedStatement;
  run<T = Record<string, unknown>>(): Promise<NanoflareD1Result<T>>;
  all<T = Record<string, unknown>>(): Promise<NanoflareD1Result<T>>;
  raw<T = unknown[]>(options?: { columnNames?: boolean }): Promise<T[]>;
  first<T = Record<string, unknown>>(columnName?: string): Promise<T | null>;
}

interface NanoflareD1DatabaseSession {
  getBookmark(): string | null;
  prepare(query: string): NanoflareD1PreparedStatement;
  batch<T = Record<string, unknown>>(
    statements: NanoflareD1PreparedStatement[],
  ): Promise<NanoflareD1Result<T>[]>;
}

interface NanoflareD1Database {
  prepare(query: string): NanoflareD1PreparedStatement;
  batch<T = Record<string, unknown>>(
    statements: NanoflareD1PreparedStatement[],
  ): Promise<NanoflareD1Result<T>[]>;
  exec(query: string): Promise<NanoflareD1ExecResult>;
  withSession(initialBookmark?: string): NanoflareD1DatabaseSession;
}

interface NanoflareAssetFetcher {
  fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

interface Env {
  ASSETS: NanoflareAssetFetcher;
  OAUTH_KV: NanoflareKVNamespace;
}
